---
- name: Installing nginx
  yum: name=nginx

- name: Copying nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Starting service
  service: name=nginx state=started enabled=yes

